# Tap-ready Homebrew Cask seed for usher (#21).
#
# This is a HAND-AUTHORED seed so the tap (github.com/georgenijo/homebrew-usher)
# is usable on day one. On every release GoReleaser OVERWRITES this file with the
# real version + per-arch sha256 and stamps "# This file was generated by
# GoReleaser. DO NOT EDIT." at the top. Its shape is kept identical to that
# generated output (verified with `goreleaser release --snapshot`) so the diff on
# the first real release is only the version/sha256, not the structure.
#
# Until the first release exists, the version + sha256 below are PLACEHOLDERS —
# `brew install --cask usher` against them WILL fail the checksum. See
# RELEASING.md. (The curl installer in scripts/install.sh prefers the universal
# usher_<ver>_darwin_all.tar.gz archive; the cask uses the thin per-arch ones.)
cask "usher" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      url "https://github.com/georgenijo/usher/releases/download/v#{version}/usher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      url "https://github.com/georgenijo/usher/releases/download/v#{version}/usher_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "usher"
  desc "MCP broker — one front desk every AI agent talks to"
  homepage "https://github.com/georgenijo/usher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usher"

  # No zap stanza required

  caveats <<~EOS
    The binary is not yet code-signed or notarized, so first run may be
    Gatekeeper-flagged. To register the always-on daemon (launchd LaunchAgent):
      usher install
    To register the default backend (GhostHands cua-driver):
      usher backend add cua -- ~/.local/bin/cua-driver mcp
  EOS
end
